import { Product, Category, Brand, Banner, AnalyticsSummary, Order } from "@/types";

export const MOCK_CATEGORIES: Category[] = [
  {
    id: "cat-fruits-veg",
    name: "Organic Fruits & Vegetables",
    slug: "organic-fruits-vegetables",
    description: "Farm-fresh organic produce harvested daily from certified farms",
    image: "https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&q=80&w=800",
    icon: "Apple",
    featured: true,
    itemCount: 120,
  },
  {
    id: "cat-dairy-bakery",
    name: "Dairy, Eggs & Bakery",
    slug: "dairy-eggs-bakery",
    description: "Pure farm milk, artisanal cheeses, organic eggs & fresh breads",
    image: "https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&q=80&w=800",
    icon: "Milk",
    featured: true,
    itemCount: 85,
  },
  {
    id: "cat-staples-grains",
    name: "Atta, Rice & Organic Staples",
    slug: "atta-rice-staples",
    description: "Handpicked premium basmati rice, organic pulses, cold-pressed oils",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&q=80&w=800",
    icon: "Wheat",
    featured: true,
    itemCount: 150,
  },
  {
    id: "cat-spices-oils",
    name: "Gourmet Spices & Cold-Pressed Oils",
    slug: "gourmet-spices-oils",
    description: "Aromatic whole spices, saffron, extra virgin olive & mustard oils",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&q=80&w=800",
    icon: "Flame",
    featured: true,
    itemCount: 95,
  },
];

export const MOCK_BRANDS: Brand[] = [
  {
    id: "b-manoj-fresh",
    name: "Manoj Farms Organic",
    logo: "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&q=80&w=200",
    description: "Our signature line of pesticide-free farm fresh organic produce.",
    featured: true,
  },
  {
    id: "b-himalayan-pure",
    name: "Himalayan Naturals",
    logo: "https://images.unsplash.com/photo-1506368249639-73a05d6f6488?auto=format&fit=crop&q=80&w=200",
    description: "Pristine mountain-harvested grains, honey, and herbal teas.",
    featured: true,
  },
  {
    id: "b-royal-organics",
    name: "Royal Organics India",
    logo: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&q=80&w=200",
    description: "Aged Royal Basmati and heritage single-origin spices.",
    featured: true,
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "p1",
    slug: "manoj-royal-aged-basmati-rice-5kg",
    name: "Manoj Royal 2-Year Aged Extra Long Basmati Rice (5kg)",
    tagline: "Pristine Aromatic Long-Grain Pearl Basmati",
    description: "Directly sourced from the foothills of the Himalayas. Aged naturally for 24 months to ensure non-sticky, fluffiest grains with unmatched natural aroma.",
    highlights: [
      "Naturally Aged for 24 Months for Maximum Length",
      "Pesticide-Tested 100% Pure Basmati Grains",
      "Extends up to 2.5x upon cooking",
      "Rich in natural nutrients & non-GMO certified"
    ],
    features: [
      "Zero artificial polish or preservatives",
      "Vacuum-sealed packaging to lock in peak freshness",
      "Ideal for Biryanis, Pulao, and gourmet rice dishes"
    ],
    price: 999,
    mrp: 1399,
    wholesalePrice: 850,
    discountPercentage: 28,
    gstPercentage: 5,
    category: "Atta, Rice & Organic Staples",
    subCategory: "Basmati Rice",
    brand: "Manoj Farms Organic",
    sku: "MT-GRO-RICE-001",
    barcode: "8901234567890",
    stock: 250,
    unit: "kg",
    inStock: true,
    weight: "5.0 kg",
    dimensions: "35x25x12 cm",
    images: [
      "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&q=80&w=800",
    ],
    variants: [
      { id: "v1-1", name: "1 kg Pack", price: 249, mrp: 320, stock: 100, unit: "kg", sku: "MT-RICE-1KG" },
      { id: "v1-2", name: "5 kg Pack", price: 999, mrp: 1399, stock: 250, unit: "kg", sku: "MT-RICE-5KG" },
      { id: "v1-3", name: "10 kg Family Pack", price: 1899, mrp: 2600, stock: 80, unit: "kg", sku: "MT-RICE-10KG" },
    ],
    specifications: [
      { key: "Grain Length", value: "8.35mm (Extra Long)" },
      { key: "Aging Period", value: "2 Years Natural Aging" },
      { key: "Origin", value: "Himalayan Foothills, India" },
      { key: "Packaging", value: "5-Layer Moisture Lock Bag" },
    ],
    rating: 4.9,
    reviewCount: 384,
    tags: ["best-seller", "organic", "rice", "staples"],
    isFeatured: true,
    isBestSeller: true,
    isTrending: true,
    isFlashSale: true,
    flashSaleEndsAt: "2026-12-31T23:59:59Z",
    createdAt: "2026-01-10T10:00:00Z",
  },
  {
    id: "p2",
    slug: "manoj-cold-pressed-virgin-mustard-oil-2l",
    name: "Manoj Farms Cold-Pressed Kachi Ghani Mustard Oil (2L)",
    tagline: "100% Pure First-Press Aromatic Mustard Oil",
    description: "Extracted traditional wood-pressed (Kachi Ghani) method without solvent extraction or chemical refining. Retains natural pungent aroma and heart-healthy Omega-3 fatty acids.",
    highlights: [
      "100% Cold Wood-Pressed Kachi Ghani Method",
      "High Pungency & Rich Natural Aroma",
      "Zero Chemicals, Solvents, or Added Preservatives",
      "Rich in Omega-3, MUFA, and Vitamin E"
    ],
    features: [
      "Single-origin yellow mustard seeds from Rajasthan",
      "Packaged in UV-protective food-grade tin container"
    ],
    price: 449,
    mrp: 599,
    wholesalePrice: 380,
    discountPercentage: 25,
    gstPercentage: 5,
    category: "Gourmet Spices & Cold-Pressed Oils",
    subCategory: "Cooking Oils",
    brand: "Manoj Farms Organic",
    sku: "MT-GRO-OIL-002",
    barcode: "8901234567891",
    stock: 180,
    unit: "L",
    inStock: true,
    weight: "2.0 L",
    dimensions: "20x15x28 cm",
    images: [
      "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&q=80&w=800",
    ],
    specifications: [
      { key: "Extraction Method", value: "Traditional Wood Ghani" },
      { key: "Seed Type", value: "A-Grade Yellow Mustard" },
      { key: "Shelf Life", value: "12 Months from Packing" },
    ],
    rating: 4.85,
    reviewCount: 219,
    tags: ["mustard-oil", "cold-pressed", "kachi-ghani"],
    isFeatured: true,
    isBestSeller: true,
    isTrending: true,
    isFlashSale: false,
    createdAt: "2026-01-12T10:00:00Z",
  },
  {
    id: "p3",
    slug: "organic-alphonso-mangoes-box-12pcs",
    name: "Manoj Organic Ratnagiri Alphonso Mangoes (1 Dozen Box)",
    tagline: "GI-Tagged Naturally Tree-Ripened Devgad Mangoes",
    description: "Handpicked GI-tagged original Ratnagiri Alphonso mangoes. Naturally ripened in grass beds without carbide chemicals. Unrivaled saffron sweetness and rich aromatic pulp.",
    highlights: [
      "100% Authentic Certified Ratnagiri GI-Tagged Alphonso",
      "Naturally Ripened in Organic Hay (Carbide Free)",
      "Uniform 250g+ Premium Export Size Fruit",
      "Insured Temperature-Controlled Express Delivery"
    ],
    features: [
      "Each fruit individually wrapped in protective foam mesh",
      "Direct farm-to-doorstep delivery within 24 hours of harvest"
    ],
    price: 1499,
    mrp: 1999,
    wholesalePrice: 1200,
    discountPercentage: 25,
    gstPercentage: 0,
    category: "Organic Fruits & Vegetables",
    subCategory: "Fresh Fruits",
    brand: "Manoj Farms Organic",
    sku: "MT-GRO-MANGO-003",
    barcode: "8901234567892",
    stock: 90,
    unit: "kg",
    inStock: true,
    weight: "3.2 kg",
    dimensions: "40x30x15 cm",
    images: [
      "https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&q=80&w=800",
    ],
    specifications: [
      { key: "Origin", value: "Ratnagiri, Maharashtra" },
      { key: "Ripening", value: "100% Natural Grass Bed" },
      { key: "Quantity", value: "12 Fruits (Box of 1 Dozen)" },
    ],
    rating: 4.95,
    reviewCount: 512,
    tags: ["alphonso", "mangoes", "fresh-fruits", "organic"],
    isFeatured: true,
    isBestSeller: true,
    isTrending: true,
    isFlashSale: true,
    flashSaleEndsAt: "2026-12-31T23:59:59Z",
    createdAt: "2026-02-01T10:00:00Z",
  },
  {
    id: "p4",
    slug: "himalayan-organic-raw-multiflora-honey-1kg",
    name: "Himalayan Raw Unpasteurized Multiflora Honey (1kg)",
    tagline: "Pure Wild Forest Nectar Harvested Above 8000ft",
    description: "Raw, unheated, and unfiltered honey extracted from wild forest beehives in the high Himalayas. Packed with natural pollen, enzymes, antioxidants, and propolis.",
    highlights: [
      "100% Raw, Unfiltered & Unpasteurized",
      "High Pollen Count & Natural Antioxidant Rich",
      "Zero Added Sugar or C4 Syrup Adulteration",
      "Glass Jar Packaging to preserve natural enzymes"
    ],
    features: [
      "NMR Tested 100% Pure Honey Certified",
      "Natural crystallisation proves raw authenticity"
    ],
    price: 799,
    mrp: 1099,
    wholesalePrice: 620,
    discountPercentage: 27,
    gstPercentage: 5,
    category: "Atta, Rice & Organic Staples",
    subCategory: "Honey & Preserves",
    brand: "Himalayan Naturals",
    sku: "MT-GRO-HONEY-004",
    barcode: "8901234567893",
    stock: 140,
    unit: "kg",
    inStock: true,
    weight: "1.0 kg",
    dimensions: "12x12x20 cm",
    images: [
      "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?auto=format&fit=crop&q=80&w=800",
    ],
    specifications: [
      { key: "Testing", value: "NMR Tested 100% Pure" },
      { key: "Origin", value: "High Himalayas, India" },
      { key: "Container", value: "Food-Grade Glass Jar" },
    ],
    rating: 4.88,
    reviewCount: 164,
    tags: ["honey", "raw-honey", "organic", "himalayan"],
    isFeatured: true,
    isBestSeller: false,
    isTrending: true,
    isFlashSale: false,
    createdAt: "2026-02-05T10:00:00Z",
  },
  {
    id: "p5",
    slug: "manoj-pure-a2-gir-cow-deshi-ghee-1l",
    name: "Manoj Farms Pure A2 Desi Gir Cow Bilona Ghee (1L)",
    tagline: "Traditional Vedic Hand-Churned Bilona Ghee",
    description: "Crafted using the ancient 5-step Vedic Bilona method from curd of grass-fed free-grazing Gir cows. Golden granular texture with divine aroma and high smoke point.",
    highlights: [
      "100% Pure A2 Beta-Casein Protein Ghee",
      "Hand-Churned from Whole Cow Curd (Bilona Method)",
      "Rich Golden Granular Texture & Nutty Aroma",
      "Boosts Immunity, Digestion & Joint Lubrication"
    ],
    features: [
      "Lab-tested zero A1 protein or palm oil dilution",
      "Free grazing grass-fed Gir cows"
    ],
    price: 1899,
    mrp: 2499,
    wholesalePrice: 1550,
    discountPercentage: 24,
    gstPercentage: 5,
    category: "Dairy, Eggs & Bakery",
    subCategory: "Desi Ghee",
    brand: "Manoj Farms Organic",
    sku: "MT-GRO-GHEE-005",
    barcode: "8901234567894",
    stock: 110,
    unit: "L",
    inStock: true,
    weight: "1.0 L",
    dimensions: "15x15x22 cm",
    images: [
      "https://images.unsplash.com/photo-1589927986089-35812388d1f4?auto=format&fit=crop&q=80&w=800",
    ],
    specifications: [
      { key: "Cow Breed", value: "Pure Indigenous Gir Cow" },
      { key: "Method", value: "Traditional Vedic Bilona" },
      { key: "Fat Type", value: "100% A2 Milk Fat" },
    ],
    rating: 4.96,
    reviewCount: 420,
    tags: ["a2-ghee", "bilona-ghee", "desi-ghee", "dairy"],
    isFeatured: true,
    isBestSeller: true,
    isTrending: true,
    isFlashSale: true,
    flashSaleEndsAt: "2026-12-31T23:59:59Z",
    createdAt: "2026-02-10T10:00:00Z",
  },
  {
    id: "p6",
    slug: "kashmiri-organic-mongra-saffron-5g",
    name: "Royal Kashmiri Organic Mongra Saffron / Kesar (5g)",
    tagline: "Grade-1 GI-Tagged Deep Red Saffron Threads",
    description: "100% pure Grade-1 Mongra saffron harvested from the Pampore fields of Kashmir. Deep crimson stigmas with high crocin content for intense aroma, color, and medicinal benefits.",
    highlights: [
      "100% Authentic Kashmiri GI-Tagged Saffron",
      "Highest Crocin & Safranal Content (Grade 1 Super-Mongra)",
      "Zero Artificial Dyes, Fibers, or Weight Agents",
      "Sealed Air-Tight Acrylic Gift Box with Holo-Seal"
    ],
    features: [
      "Ideal for pregnancy, milk, sweets, biryani, and ayurvedic remedies",
      "Tested ISO 3632 Saffron Purity Compliant"
    ],
    price: 1999,
    mrp: 2799,
    wholesalePrice: 1600,
    discountPercentage: 28,
    gstPercentage: 5,
    category: "Gourmet Spices & Cold-Pressed Oils",
    subCategory: "Exotic Spices",
    brand: "Royal Organics India",
    sku: "MT-GRO-SAFFRON-006",
    barcode: "8901234567895",
    stock: 65,
    unit: "g",
    inStock: true,
    weight: "5 g",
    dimensions: "8x8x5 cm",
    images: [
      "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&q=80&w=800",
    ],
    specifications: [
      { key: "Grade", value: "Grade-1 Super Mongra" },
      { key: "Origin", value: "Pampore, Kashmir" },
      { key: "Certification", value: "Kashmir GI Tagged" },
    ],
    rating: 4.97,
    reviewCount: 280,
    tags: ["saffron", "kesar", "kashmiri", "spices"],
    isFeatured: true,
    isBestSeller: true,
    isTrending: false,
    isFlashSale: false,
    createdAt: "2026-02-15T10:00:00Z",
  },
];

export const MOCK_BANNERS: Banner[] = [
  {
    id: "b1",
    title: "100% Farm Fresh Organic Groceries Delivered in 24 Hours",
    subtitle: "Pesticide-Free Produce, A2 Gir Bilona Ghee & Royal Basmati Rice Direct to Your Doorstep",
    badge: "FARM TO TABLE FRESH",
    ctaText: "Shop Organic Supermarket",
    ctaLink: "/shop",
    imageUrl: "https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&q=80&w=1600",
    active: true,
  },
  {
    id: "b2",
    title: "Pure Cold-Pressed Oils & Heritage Kashmiri Spices",
    subtitle: "Traditional Kachi Ghani Wood-Pressed Oils & GI-Tagged Saffron",
    badge: "HEALTH & WELLNESS",
    ctaText: "Explore Gourmet Spices",
    ctaLink: "/shop?category=gourmet-spices-oils",
    imageUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&q=80&w=1600",
    active: true,
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: "ord-8812",
    orderNumber: "MT-2026-8812",
    userId: "usr-1",
    customerName: "Priya Sharma",
    customerEmail: "priya.sharma@example.com",
    customerPhone: "+91 98200 11223",
    items: [
      {
        productId: "p1",
        name: "Manoj Royal 2-Year Aged Extra Long Basmati Rice (5kg)",
        image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&q=80&w=400",
        price: 999,
        quantity: 2,
      },
      {
        productId: "p5",
        name: "Manoj Farms Pure A2 Desi Gir Cow Bilona Ghee (1L)",
        image: "https://images.unsplash.com/photo-1589927986089-35812388d1f4?auto=format&fit=crop&q=80&w=400",
        price: 1899,
        quantity: 1,
      },
    ],
    shippingAddress: {
      id: "addr-1",
      fullName: "Priya Sharma",
      phone: "+91 98200 11223",
      streetAddress: "Flat 402, Seawood Towers, Bandra West",
      city: "Mumbai",
      state: "Maharashtra",
      pincode: "400050",
      country: "India",
      isDefault: true,
      type: "Home",
    },
    billingAddress: {
      id: "addr-1",
      fullName: "Priya Sharma",
      phone: "+91 98200 11223",
      streetAddress: "Flat 402, Seawood Towers, Bandra West",
      city: "Mumbai",
      state: "Maharashtra",
      pincode: "400050",
      country: "India",
      isDefault: true,
      type: "Home",
    },
    subtotal: 3897,
    tax: 194,
    shippingFee: 0,
    discount: 300,
    total: 3791,
    paymentMethod: "Razorpay",
    paymentStatus: "Paid",
    status: "Delivered",
    trackingNumber: "EXP-IND-994812",
    estimatedDelivery: "2026-08-04",
    createdAt: "2026-08-01T14:30:00Z",
    updatedAt: "2026-08-04T11:00:00Z",
    timeline: [
      { status: "Placed", timestamp: "2026-08-01T14:30:00Z", note: "Order received successfully" },
      { status: "Confirmed", timestamp: "2026-08-01T15:00:00Z", note: "Fresh inventory reserved" },
      { status: "Packed", timestamp: "2026-08-02T09:00:00Z", note: "Moisture-proof packed" },
      { status: "Shipped", timestamp: "2026-08-02T16:00:00Z", note: "Handed over to Express Courier" },
      { status: "Delivered", timestamp: "2026-08-04T11:00:00Z", note: "Delivered to customer" },
    ],
  },
];

export const MOCK_ANALYTICS: AnalyticsSummary = {
  todayRevenue: 148500,
  monthlyRevenue: 4250000,
  yearlyRevenue: 48900000,
  totalOrders: 3240,
  totalCustomers: 8900,
  conversionRate: 4.8,
  avgOrderValue: 1312,
  revenueByMonth: [
    { month: "Jan", revenue: 3200000, sales: 2400 },
    { month: "Feb", revenue: 3600000, sales: 2750 },
    { month: "Mar", revenue: 3900000, sales: 2900 },
    { month: "Apr", revenue: 4100000, sales: 3100 },
    { month: "May", revenue: 4400000, sales: 3350 },
    { month: "Jun", revenue: 4600000, sales: 3500 },
    { month: "Jul", revenue: 4250000, sales: 3240 },
  ],
  salesByCategory: [
    { name: "Atta, Rice & Staples", value: 1850000 },
    { name: "Dairy, Eggs & Bakery", value: 1100000 },
    { name: "Cold-Pressed Oils & Spices", value: 850000 },
    { name: "Organic Fruits & Veg", value: 450000 },
  ],
  inventoryStatus: [
    { category: "Atta & Rice", inStock: 450, lowStock: 12 },
    { category: "Dairy & Ghee", inStock: 280, lowStock: 5 },
    { category: "Cold-Pressed Oils", inStock: 340, lowStock: 8 },
    { category: "Fresh Mangoes & Fruits", inStock: 90, lowStock: 25 },
  ],
};
